# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hhh2.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(998, 919)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(900, 190, 80, 31))
        self.pushButton.setObjectName("pushButton")
        self.show_read_2 = QtWidgets.QLabel(self.centralwidget)
        self.show_read_2.setGeometry(QtCore.QRect(910, 90, 64, 64))
        self.show_read_2.setStyleSheet("background-color: rgb(245, 250, 246);")
        self.show_read_2.setText("")
        self.show_read_2.setObjectName("show_read_2")
        self.show_read = QtWidgets.QLabel(self.centralwidget)
        self.show_read.setGeometry(QtCore.QRect(170, 60, 711, 171))
        self.show_read.setStyleSheet("background-color: rgb(245, 250, 246);")
        self.show_read.setText("")
        self.show_read.setObjectName("show_read")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(170, 280, 201, 27))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.select_txt_Button = QtWidgets.QPushButton(self.centralwidget)
        self.select_txt_Button.setGeometry(QtCore.QRect(10, 130, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.select_txt_Button.setFont(font)
        self.select_txt_Button.setObjectName("select_txt_Button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 0, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(239, 41, 41);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(760, 60, 111, 19))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(900, 60, 91, 19))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(170, 320, 521, 521))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.feature_visualize_Button = QtWidgets.QPushButton(self.centralwidget)
        self.feature_visualize_Button.setGeometry(QtCore.QRect(10, 500, 151, 21))
        self.feature_visualize_Button.setObjectName("feature_visualize_Button")
        self.select_model = QtWidgets.QLabel(self.centralwidget)
        self.select_model.setGeometry(QtCore.QRect(50, 280, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.select_model.setFont(font)
        self.select_model.setObjectName("select_model")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 998, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "数据可视化"))
        self.comboBox.setItemText(0, _translate("MainWindow", "一维卷积神经网络模型"))
        self.comboBox.setItemText(1, _translate("MainWindow", "二维卷积神经网络模型"))
        self.comboBox.setItemText(2, _translate("MainWindow", "基于支持向量机的模型"))
        self.select_txt_Button.setText(_translate("MainWindow", "选取文件"))
        self.label.setText(_translate("MainWindow", "基于深度学习的核素识别系统"))
        self.label_2.setText(_translate("MainWindow", "一维能谱波形图"))
        self.label_3.setText(_translate("MainWindow", "二维能谱图像"))
        self.feature_visualize_Button.setText(_translate("MainWindow", "特征可视化"))
        self.select_model.setText(_translate("MainWindow", "选取模型"))


